### ISSUE TITLE
[bug] pcs config shows nothing

### ISSUE THREAD

**Issue by beinbliss** [feist/pcs#63]
Hello,

os: centos 6.6
pcs: pcs-0.9.123-9.0.1.el6.centos.2.x86_64
cman is not being used

#pcs config
Cluster Name: 
Traceback (most recent call last):
  File "/usr/sbin/pcs", line 138, in <module>
    main(sys.argv[1:])
  File "/usr/sbin/pcs", line 132, in main
    cluster.print_config()
  File "/usr/lib/python2.6/site-packages/pcs/cluster.py", line 890, in print_config
    status.nodes_status(["config"])
  File "/usr/lib/python2.6/site-packages/pcs/status.py", line 65, in nodes_status
    corosync_nodes = utils.getNodesFromCorosyncConf()
  File "/usr/lib/python2.6/site-packages/pcs/utils.py", line 310, in getNodesFromCorosyncConf
    dom = parse(settings.cluster_conf_file)
  File "/usr/lib64/python2.6/xml/dom/minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "/usr/lib64/python2.6/xml/dom/expatbuilder.py", line 924, in parse
    result = builder.parseFile(fp)
  File "/usr/lib64/python2.6/xml/dom/expatbuilder.py", line 211, in parseFile
    parser.Parse("", True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

shouldn't it output config with existing corosync.conf ?

**Comment by jnpkrn** [comment]
Both stock cluster stacks in RHEL 6 family do make a use of CMAN (which makes Corosync bypass corosync.conf) and hence cluster.conf is naturally an expected source for the reference data.  RHEL 7 family matches your expectations but pcs is accustomed to that as well.

**Comment by beinbliss** [comment]
I have browsed pcs code and i saw that in case cluster.conf is empty or non existent then read corosync.conf. But in this case - it does not do so. It sees that cluster.conf is not existent and stops at that point instead of reading corosync.conf and proceeding. I.e. clean output:
# pcs config
Cluster Name: 
Error: Unable to open cluster.conf file to get nodes list

in getNodesFromCorosyncConf() function

**Comment by tomjelinek** [comment]
Hello, I changed cman/corosync detection in https://github.com/feist/pcs/commit/9e19af588be49ee7c11a158e01c23dffc33791fe, which (hopefully) fixes this issue.
