### ISSUE TITLE
IndexError: list index out of range if corosync.service (systemd) file doesn't exists

### ISSUE THREAD

**Issue by goldyfruit** [feist/pcs#69]
Hi,

If the **corosync.service** systemd file doesn't exists, the pcs status command return a Python backtrace:
```
Cluster name: c001
WARNING: no stonith devices and stonith-enabled is not false
Last updated: Mon Nov  9 10:34:34 2015
Last change: Sun Nov  8 22:58:13 2015
Stack: corosync
Current DC: ctrl01 (1) - partition with quorum
Version: 1.1.12-561c4cf
2 Nodes configured
0 Resources configured


Online: [ ctrl01 ctrl02 ]

Full list of resources:


PCSD Status:
  ctrl01: Offline
  ctrl02: Offline

Daemon Status:
  corosync: unknown/Failed to get unit file state for corosync.service: No such file or directory
  pacemaker: unknown/
Traceback (most recent call last):
  File "/usr/sbin/pcs", line 221, in <module>
    main(sys.argv[1:])
  File "/usr/sbin/pcs", line 161, in main
    cmd_map[command](argv)
  File "/usr/lib/python2.7/dist-packages/pcs/status.py", line 16, in status_cmd
    full_status()
  File "/usr/lib/python2.7/dist-packages/pcs/status.py", line 64, in full_status
    utils.serviceStatus("  ")
  File "/usr/lib/python2.7/dist-packages/pcs/utils.py", line 1979, in serviceStatus
    print prefix + daemons[i] + ": " + status[i] + "/" + enabled[i]
IndexError: list index out of range
```
When I create the file, I don't have this Python error anymore.
```
Cluster name: c001
Last updated: Mon Nov  9 10:43:35 2015
Last change: Mon Nov  9 10:35:10 2015
Stack: corosync
Current DC: ctrl01 (1) - partition with quorum
Version: 1.1.12-561c4cf
2 Nodes configured
0 Resources configured


Online: [ ctrl01 ctrl02 ]

Full list of resources:


PCSD Status:
  ctrl01: Offline
  ctrl02: Offline

Daemon Status:
  corosync: unknown/Failed to get unit file state for pacemaker.service: No such file or directory
  pacemaker: unknown/disabled
  pcsd: active/
```
I'm using Debian Jessie.

Thanks guys.

**Comment by tomjelinek** [comment]
Hi @goldyfruit,
This has been fixed by https://github.com/feist/pcs/commit/3d45b362ea56ec9f4b407592d809d59ab2735aa1

Thanks for reporting the issue.
