### ISSUE TITLE
Question : The start/stop command of pcs sometimes fails.

### ISSUE THREAD

**Issue by HideoYamauchi** [feist/pcs#83]
Hi All,

When I use pcsd on RHEL6.7, start and stop and setup command are not sometimes completed.
It does not seem to occur on RHEL7.2.

The first practice was not completed.
Several minutes later, I stopped it by the interrupt of the keyboard.
[root@rh67-01 ~]# pcs cluster start --all
^CTraceback (most recent call last):
  File "/usr/sbin/pcs", line 229, in <module>
    main(sys.argv[1:])
  File "/usr/sbin/pcs", line 169, in main
    cmd_map[command](argv)
  File "/usr/lib/python2.6/site-packages/pcs/cluster.py", line 68, in cluster_cmd
    start_cluster_all()
  File "/usr/lib/python2.6/site-packages/pcs/cluster.py", line 1007, in start_cluster_all
    start_cluster_nodes(utils.getNodesFromCorosyncConf())
  File "/usr/lib/python2.6/site-packages/pcs/cluster.py", line 1013, in start_cluster_nodes
    error_list = utils.run_node_threads(threads)
  File "/usr/lib/python2.6/site-packages/pcs/utils.py", line 904, in run_node_threads
    thread.join(1)
  File "/usr/lib64/python2.6/threading.py", line 655, in join
    self.__block.wait(delay)
  File "/usr/lib64/python2.6/threading.py", line 258, in wait
    _sleep(delay)
KeyboardInterrupt

The second practice was completed.
[root@rh67-01 ~]# pcs cluster start --all
rh67-02: Starting Cluster...
rh67-01: Starting Cluster...

Is there the idea of any cause?

Best Regards,
Hideo Yamauchi.

**Comment by tomjelinek** [comment]
Hi Hideo,

There is a recent fix for this kind of issues: https://github.com/feist/pcs/commit/59dde9ba191bc079aee08ac25576b51b9a85681c. Does it help?

Best Regards,
Tomas

**Comment by HideoYamauchi** [comment]
Hi Tomas,

I will try whether a problem is settled by your correction next week.
I inform you of a result.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Because a discussion was over, this is closed.
