### ISSUE TITLE
Running ./pcs from git master with python2 errors out

### ISSUE THREAD

**Issue by mbaldessari** [feist/pcs#92]
I usually run pcs straight from the git directory when looking at sosreport. I updated today to master
and it seems to break:
./pcs 
Traceback (most recent call last):
  File "./pcs", line 10, in <module>
    from pcs import app
  File "/home/michele/Devel/pcs/pcs/app.py", line 14, in <module>
    from pcs import (
  File "/home/michele/Devel/pcs/pcs/acl.py", line 10, in <module>
    from pcs import (
  File "/home/michele/Devel/pcs/pcs/prop.py", line 13, in <module>
    from pcs import utils
  File "/home/michele/Devel/pcs/pcs/utils.py", line 58, in <module>
    from pcs import settings, usage
  File "/home/michele/Devel/pcs/pcs/settings.py", line 1, in <module>
    from pcs.settings_default import *
  File "/home/michele/Devel/pcs/pcs/pcs.py", line 6, in <module>
  File "/home/michele/Devel/pcs/pcs/cluster.py", line 25, in <module>
    from pcs import (
  File "/home/michele/Devel/pcs/pcs/constraint.py", line 15, in <module>
    from pcs import (
  File "/home/michele/Devel/pcs/pcs/rule.py", line 11, in <module>
    from pcs import utils
ImportError: cannot import name utils

Note that if I switch to python3 it all works. Feel free to close if this use-case is not interesting

**Comment by tomjelinek** [comment]
Hi Michele,

Try to delete all `*.pyc`, `*.pyo` files and `__pycache__` directories in your pcs directory and all its subdirectories.

**Comment by mbaldessari** [comment]
Hi Tomas,

a righto. Brainfart on my part then. Sorry about the noise.

Thanks,
Michele
